// <auto-generated />
using System;
using MIS_InventoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MIS_InventoryManagement.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20250524095711_Misinventory")]
    partial class Misinventory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MIS_InventoryManagement.Models.Accessories", b =>
                {
                    b.Property<int>("AccessoriesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessoriesID"), 1L, 1);

                    b.Property<string>("AddBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capasity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PC_SLNO")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("VandorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccessoriesID");

                    b.HasIndex("PC_SLNO");

                    b.HasIndex("StaffId");

                    b.ToTable("Accessories");
                });

            modelBuilder.Entity("MIS_InventoryManagement.Models.PcInformation", b =>
                {
                    b.Property<int>("SlNo")
                        .HasColumnType("int");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Generation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Hhd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModelNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ram")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ssd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StafId")
                        .HasColumnType("int");

                    b.Property<string>("VandorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SlNo");

                    b.HasIndex("StafId");

                    b.ToTable("PcInformations");
                });

            modelBuilder.Entity("MIS_InventoryManagement.Models.StafInformation", b =>
                {
                    b.Property<int>("StafId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dpt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StafId");

                    b.ToTable("StafInformations");
                });

            modelBuilder.Entity("MIS_InventoryManagement.Models.Accessories", b =>
                {
                    b.HasOne("MIS_InventoryManagement.Models.PcInformation", "Pc")
                        .WithMany("Accessories")
                        .HasForeignKey("PC_SLNO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MIS_InventoryManagement.Models.StafInformation", "Staf")
                        .WithMany("Accessories")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pc");

                    b.Navigation("Staf");
                });

            modelBuilder.Entity("MIS_InventoryManagement.Models.PcInformation", b =>
                {
                    b.HasOne("MIS_InventoryManagement.Models.StafInformation", "Staf")
                        .WithMany("PcInformations")
                        .HasForeignKey("StafId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staf");
                });

            modelBuilder.Entity("MIS_InventoryManagement.Models.PcInformation", b =>
                {
                    b.Navigation("Accessories");
                });

            modelBuilder.Entity("MIS_InventoryManagement.Models.StafInformation", b =>
                {
                    b.Navigation("Accessories");

                    b.Navigation("PcInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
